runtime: python39
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /query
  script: auto

- url: /add_data
  script: auto

- url: /retailers/login
  script: auto

- url: /retailers/signup
  script: auto
